import type { Dispatch, MouseEvent as ReactMouseEvent, RefObject, SetStateAction } from "react";
import type { MotionDocScene } from "@/core/motion-doc/domain/motionDocParser";
import type { AddBlockOptions, FrameUpdate } from "@/features/studio/application/motionDocCommands";
import type { SlideRow } from "@/features/studio/ui/LayerSidebar";
import type { AddBlockType } from "@/features/studio/ui/studioOptions";

export type SelectionMdx = { label: string; source: string };

export type StudioWorkspaceProps = {
  activeSlide: MotionDocScene | undefined;
  activeSlideAccent: string;
  activeSlideAlignX: string;
  activeSlideAlignY: string;
  activeSlideBackground: string;
  activeSlideIndex: number;
  activeSlideLayout: string;
  activeSlideMutedColor: string;
  activeSlideShader: string;
  activeSlideShaderColor1: string;
  activeSlideShaderColor2: string;
  activeSlideShaderColor3: string;
  activeSlideShaderDetail: number;
  activeSlideShaderEngine: string;
  activeSlideShaderIntensity: number;
  activeSlideShaderScale: number;
  activeSlideShaderSoftness: number;
  activeSlideShaderSpeed: number;
  activeSlideTextColor: string;
  activeSlideTheme: string;
  addBlockToActiveSlide: (type: AddBlockType, options?: AddBlockOptions) => void;
  addSlide: () => void;
  addSlideWithLayout: (layoutSource: string) => void;
  addTextAtPosition: (position: { x: number; y: number }) => void;
  applyTemplate: (templateId: string) => void;
  beginBlockTransform: () => void;
  canvasSource: string;
  clearBlockSelection: () => void;
  commitMdxSource: (value: string) => void;
  copySource: () => Promise<void>;
  deleteBlock: (blockIndex: number) => void;
  deleteSlide: (slideIndex: number) => void;
  draggedBlockIndex: number | null;
  dragOverBlockIndex: number | null;
  exportHtmlFile: () => void;
  exportMdxFile: () => void;
  exportMenuRef: RefObject<HTMLDivElement | null>;
  goToNextSlide: () => void;
  goToPreviousSlide: () => void;
  insertSnippet: (code: string) => void;
  isCanvasGridVisible: boolean;
  isCodeEditorOpen: boolean;
  isExportMenuOpen: boolean;
  isMobileInspectorOpen: boolean;
  isMobileSidebarOpen: boolean;
  isProjectDirty: boolean;
  isTemplateModalOpen: boolean;
  moveBlock: (blockIndex: number, direction: -1 | 1) => void;
  newProject: () => void;
  notice: string;
  projectName: string;
  pushUndoSnapshot: () => void;
  reorderBlock: (fromIndex: number, toIndex: number) => void;
  reorderSlide: (fromIndex: number, toIndex: number) => void;
  replayNonce: number;
  scenes: MotionDocScene[];
  selectBlock: (index: number, options?: { additive?: boolean; range?: boolean }) => void;
  selectBlockFromLayer: (index: number, event: ReactMouseEvent<HTMLDivElement>) => void;
  selectBlocks: (indices: number[], options?: { additive?: boolean }) => void;
  selectedBlockIndex: number | null;
  selectedBlockIndices: number[];
  selectedTemplateId: string;
  selectionMdx: SelectionMdx;
  selectSingleBlock: (index: number | null) => void;
  setActiveSlideIndex: Dispatch<SetStateAction<number>>;
  setDraggedBlockIndex: Dispatch<SetStateAction<number | null>>;
  setDragOverBlockIndex: Dispatch<SetStateAction<number | null>>;
  setIsCanvasGridVisible: Dispatch<SetStateAction<boolean>>;
  setIsCodeEditorOpen: Dispatch<SetStateAction<boolean>>;
  setIsExportMenuOpen: Dispatch<SetStateAction<boolean>>;
  setIsMobileInspectorOpen: Dispatch<SetStateAction<boolean>>;
  setIsMobileSidebarOpen: Dispatch<SetStateAction<boolean>>;
  setIsTemplateModalOpen: Dispatch<SetStateAction<boolean>>;
  setReplayNonce: Dispatch<SetStateAction<number>>;
  slideRows: SlideRow[];
  source: string;
  totalDuration: number;
  undoLastChange: () => void;
  updateActiveSlideStyle: (updates: {
    background?: string;
    theme?: string;
  }) => void;
  updateAllSlidesStyle: (updates: Record<string, string | number>) => void;
  updateBlock: (blockIndex: number, newProps: Record<string, string | number>, newText?: string) => void;
  updatePositionedBlockFrames: (updates: FrameUpdate[], commit?: boolean) => void;
  updateSelectionMdx: (value: string) => void;
  uploadImageForBlock: (blockIndex: number, file: File | undefined) => void;
  uploadVideoForBlock: (blockIndex: number, file: File | undefined) => void;
};
