import type { Dispatch, MouseEvent as ReactMouseEvent, ReactNode, RefObject, SetStateAction } from "react";
import type { MotionDocProps, MotionDocScene } from "@/core/motion-doc/domain/motionDocTypes";
import type { CanvasTool } from "@/features/pitch/application/canvasTools";
import type { AddBlockOptions, InsertSlidePlacement } from "@/features/pitch/application/motionDocCommands";
import type { BlockUpdater } from "@/features/pitch/application/pitchCommandTypes";
import type { BlockFramePatch } from "@/features/pitch/application/pitchGeometry";
import type { SlideComment } from "@/features/pitch/application/slideComments";
import type { SlideRow } from "@/features/pitch/application/slideRows";
import type { AddBlockType } from "@/features/pitch/ui/pitchOptions";

export type SelectionMdx = { label: string; source: string };

export type PitchWorkspaceAgent = {
  isEnabled: boolean;
  isPanelOpen: boolean;
  panel?: ReactNode;
  togglePanel: () => void;
};

export type PitchWorkspaceDocument = {
  activeSlide: MotionDocScene | undefined;
  activeSlideAccent: string;
  activeSlideBackground: string;
  activeSlideComments: SlideComment[];
  activeSlideIndex: number;
  activeSlideLayoutPreset: string;
  activeSlideMutedColor: string;
  activeSlideShader: string;
  activeSlideShaderAngle: number;
  activeSlideShaderColor1: string;
  activeSlideShaderColor2: string;
  activeSlideShaderColor3: string;
  activeSlideShaderColor4: string;
  activeSlideShaderColor5: string;
  activeSlideShaderColor6: string;
  activeSlideShaderDetail: number;
  activeSlideShaderEngine: string;
  activeSlideShaderIntensity: number;
  activeSlideShaderPreset: string;
  activeSlideShaderScale: number;
  activeSlideShaderSoftness: number;
  activeSlideShaderSpeed: number;
  activeSlideTextColor: string;
  activeSlideTheme: string;
  canvasSource: string;
  isProjectDirty: boolean;
  projectName: string;
  scenes: MotionDocScene[];
  selectedTemplateId: string;
  slideRows: SlideRow[];
  source: string;
  totalDuration: number;
};

export type PitchWorkspaceSelection = {
  clearBlockSelection: () => void;
  draggedBlockIndex: number | null;
  dragOverBlockIndex: number | null;
  hasCopiedBlock: boolean;
  selectBlock: (index: number, options?: { additive?: boolean; range?: boolean }) => void;
  selectBlockFromLayer: (index: number, event: ReactMouseEvent<HTMLDivElement>) => void;
  selectBlocks: (indices: number[], options?: { additive?: boolean }) => void;
  selectedBlockIndex: number | null;
  selectedBlockIndices: number[];
  selectedBlocksLocked: boolean;
  selectionMdx: SelectionMdx;
  selectSingleBlock: (index: number | null) => void;
  setDraggedBlockIndex: Dispatch<SetStateAction<number | null>>;
  setDragOverBlockIndex: Dispatch<SetStateAction<number | null>>;
};

export type PitchWorkspaceCommands = {
  addBlockToActiveSlide: (type: AddBlockType, options?: AddBlockOptions) => void;
  addSlide: () => void;
  applyLayoutToActiveSlide: (layoutSource: string, layoutId: string) => void;
  applyTemplate: (templateId: string) => void;
  beginBlockTransform: () => void;
  commitMdxSource: (value: string) => void;
  copySelectedBlock: () => void;
  copySource: () => Promise<void>;
  deleteBlock: (blockIndex: number) => void;
  deleteSelectedBlocks: () => void;
  deleteSlide: (slideIndex: number) => void;
  duplicateSelectedBlock: () => void;
  goToNextSlide: () => void;
  goToPreviousSlide: () => void;
  groupSelectedBlocks: () => void;
  imageSourceRequiresAbsoluteUrl: boolean;
  importImageUrlForBlock: (blockIndex: number, source: string) => boolean;
  insertSlideNearActive: (placement: InsertSlidePlacement) => void;
  moveBlock: (blockIndex: number, direction: -1 | 1) => void;
  moveBlockToEdge: (blockIndex: number, edge: "back" | "front") => void;
  moveSelectedBlocksToEdge: (edge: "back" | "front") => void;
  newProject: () => void;
  onAddActiveSlideComment: (comment: string) => void;
  onPassActiveSlideComment: (commentId: string) => void;
  openExport: () => void;
  openPresentationPreview: () => void;
  pasteCopiedBlock: () => void;
  pushUndoSnapshot: () => void;
  removeImageForBlock: (blockIndex: number) => void;
  requestImageRemoval: () => boolean;
  requestImageUpload: () => boolean;
  renameBlock: (blockIndex: number, name: string) => void;
  reorderBlock: (fromIndex: number, toIndex: number) => void;
  reorderSlide: (fromIndex: number, toIndex: number) => void;
  setActiveSlideIndex: Dispatch<SetStateAction<number>>;
  toggleBlockPositionLock: (blockIndex: number) => void;
  toggleSelectedBlocksPositionLock: () => void;
  undoLastChange: () => void;
  ungroupSelectedBlocks: () => void;
  updateActiveSlideStyle: (updates: MotionDocProps) => void;
  updateAllSlidesStyle: (updates: MotionDocProps) => void;
  updateBlock: BlockUpdater;
  updatePositionedBlockFrames: (updates: BlockFramePatch[]) => void;
  updateSelectionMdx: (value: string) => void;
  uploadImageForBlock: (blockIndex: number, file: File | undefined) => void;
  useSelectedImageAsBackground: () => void;
};

export type PitchWorkspaceView = {
  accessMode: "authenticated" | "guest";
  activeCanvasTool: CanvasTool;
  exportMenuRef: RefObject<HTMLDivElement | null>;
  isCanvasGridVisible: boolean;
  isCodeEditorOpen: boolean;
  isExportMenuOpen: boolean;
  isMobileInspectorOpen: boolean;
  isMobileSidebarOpen: boolean;
  isTemplateModalOpen: boolean;
  notice: string;
  replayNonce: number;
  setActiveCanvasTool: Dispatch<SetStateAction<CanvasTool>>;
  setIsCanvasGridVisible: Dispatch<SetStateAction<boolean>>;
  setIsCodeEditorOpen: Dispatch<SetStateAction<boolean>>;
  setIsExportMenuOpen: Dispatch<SetStateAction<boolean>>;
  setIsMobileInspectorOpen: Dispatch<SetStateAction<boolean>>;
  setIsMobileSidebarOpen: Dispatch<SetStateAction<boolean>>;
  setIsTemplateModalOpen: Dispatch<SetStateAction<boolean>>;
};

export type PitchWorkspaceProps = {
  agent?: PitchWorkspaceAgent;
  commands: PitchWorkspaceCommands;
  document: PitchWorkspaceDocument;
  selection: PitchWorkspaceSelection;
  view: PitchWorkspaceView;
};
