import type { Dispatch, MouseEvent as ReactMouseEvent, ReactNode, RefObject, SetStateAction } from "react";
import type { MotionDocScene } from "@/core/motion-doc/domain/motionDocParser";
import type { CanvasTool } from "@/features/pitch/application/canvasTools";
import type { SlideComment } from "@/features/pitch/application/slideComments";
import type { AddBlockOptions, FrameUpdate, InsertSlidePlacement } from "@/features/pitch/application/motionDocCommands";
import type { SlideRow } from "@/features/pitch/ui/LayerSidebar";
import type { BlockUpdater } from "@/features/pitch/ui/pitchCommandTypes";
import type { AddBlockType } from "@/features/pitch/ui/pitchOptions";

export type SelectionMdx = { label: string; source: string };

export type PitchWorkspaceProps = {
  agentPanel?: ReactNode;
  activeSlide: MotionDocScene | undefined;
  activeSlideAccent: string;
  activeSlideAlignX: string;
  activeSlideAlignY: string;
  activeSlideBackground: string;
  activeSlideIndex: number;
  activeSlideLayout: string;
  activeSlideLayoutPreset: string;
  activeSlideMutedColor: string;
  activeSlideComments: SlideComment[];
  activeSlideShader: string;
  activeSlideShaderAngle: number;
  activeSlideShaderColor1: string;
  activeSlideShaderColor2: string;
  activeSlideShaderColor3: string;
  activeSlideShaderColor4: string;
  activeSlideShaderColor5: string;
  activeSlideShaderColor6: string;
  activeSlideShaderDetail: number;
  activeSlideShaderEngine: string;
  activeSlideShaderIntensity: number;
  activeSlideShaderPreset: string;
  activeSlideShaderScale: number;
  activeSlideShaderSoftness: number;
  activeSlideShaderSpeed: number;
  activeSlideTextColor: string;
  activeSlideTheme: string;
  activeCanvasTool: CanvasTool;
  addBlockToActiveSlide: (type: AddBlockType, options?: AddBlockOptions) => void;
  addSlide: () => void;
  applyLayoutToActiveSlide: (layoutSource: string, layoutId: string) => void;
  applyTemplate: (templateId: string) => void;
  beginBlockTransform: () => void;
  canvasSource: string;
  clearBlockSelection: () => void;
  commitMdxSource: (value: string) => void;
  copySource: () => Promise<void>;
  copySelectedBlock: () => void;
  deleteBlock: (blockIndex: number) => void;
  deleteSelectedBlocks: () => void;
  deleteSlide: (slideIndex: number) => void;
  duplicateSelectedBlock: () => void;
  groupSelectedBlocks: () => void;
  draggedBlockIndex: number | null;
  dragOverBlockIndex: number | null;

  exportMenuRef: RefObject<HTMLDivElement | null>;
  goToNextSlide: () => void;
  goToPreviousSlide: () => void;
  insertSnippet: (code: string) => void;
  insertSlideNearActive: (placement: InsertSlidePlacement) => void;
  isCanvasGridVisible: boolean;
  isAgentEnabled: boolean;
  isAgentPanelOpen: boolean;
  isCodeEditorOpen: boolean;
  isExportMenuOpen: boolean;
  isMobileInspectorOpen: boolean;
  isMobileSidebarOpen: boolean;
  isProjectDirty: boolean;
  isTemplateModalOpen: boolean;
  hasCopiedBlock: boolean;
  moveBlock: (blockIndex: number, direction: -1 | 1) => void;
  moveBlockToEdge: (blockIndex: number, edge: "back" | "front") => void;
  moveSelectedBlocksToEdge: (edge: "back" | "front") => void;
  newProject: () => void;
  notice: string;
  openPresentationPreview: () => void;
  onAddActiveSlideComment: (comment: string) => void;
  onPassActiveSlideComment: (commentId: string) => void;
  projectName: string;
  pushUndoSnapshot: () => void;
  pasteCopiedBlock: () => void;
  reorderBlock: (fromIndex: number, toIndex: number) => void;
  reorderSlide: (fromIndex: number, toIndex: number) => void;
  replayNonce: number;
  scenes: MotionDocScene[];
  selectBlock: (index: number, options?: { additive?: boolean; range?: boolean }) => void;
  selectBlockFromLayer: (index: number, event: ReactMouseEvent<HTMLDivElement>) => void;
  selectBlocks: (indices: number[], options?: { additive?: boolean }) => void;
  selectedBlockIndex: number | null;
  selectedBlockIndices: number[];
  selectedBlocksLocked: boolean;
  selectedTemplateId: string;
  selectionMdx: SelectionMdx;
  selectSingleBlock: (index: number | null) => void;
  setActiveSlideIndex: Dispatch<SetStateAction<number>>;
  setActiveCanvasTool: Dispatch<SetStateAction<CanvasTool>>;
  setDraggedBlockIndex: Dispatch<SetStateAction<number | null>>;
  setDragOverBlockIndex: Dispatch<SetStateAction<number | null>>;
  setIsCanvasGridVisible: Dispatch<SetStateAction<boolean>>;
  setIsCodeEditorOpen: Dispatch<SetStateAction<boolean>>;
  setIsExportMenuOpen: Dispatch<SetStateAction<boolean>>;
  setIsMobileInspectorOpen: Dispatch<SetStateAction<boolean>>;
  setIsMobileSidebarOpen: Dispatch<SetStateAction<boolean>>;
  setIsTemplateModalOpen: Dispatch<SetStateAction<boolean>>;
  setReplayNonce: Dispatch<SetStateAction<number>>;
  slideRows: SlideRow[];
  source: string;
  toggleSelectedBlocksPositionLock: () => void;
  toggleAgentPanel: () => void;
  toggleBlockPositionLock: (blockIndex: number) => void;
  ungroupSelectedBlocks: () => void;
  renameBlock: (blockIndex: number, name: string) => void;
  totalDuration: number;
  undoLastChange: () => void;
  updateActiveSlideStyle: (updates: {
    background?: string;
    theme?: string;
  }) => void;
  updateAllSlidesStyle: (updates: Record<string, string | number>) => void;
  updateBlock: BlockUpdater;
  updatePositionedBlockFrames: (updates: FrameUpdate[]) => void;
  updateSelectionMdx: (value: string) => void;
  useSelectedImageAsBackground: () => void;
  uploadImageForBlock: (blockIndex: number, file: File | undefined) => void;
  uploadVideoForBlock: (blockIndex: number, file: File | undefined) => void;
};
