import type { SectionGroup, SectionType } from "@/features/briefly/domain/briefTypes";

export type BrieflyLocale = "zh-TW" | "en";

export const brieflyCopy = {
  "zh-TW": {
    landing: {
      heroBody: "使用 MDX 更快建立 Project Brief，把零散想法整理成結構化專案企劃，直接在文件畫布中預覽，最後匯出 MDX 或 HTML。",
      primaryCta: "開始使用 SlideX Briefly",
      secondaryCta: "探索功能",
      mcpInstallEyebrow: "Briefly MCP Server",
      mcpInstallTitle: "用 npm 安裝 Briefly MCP。",
      mcpInstallBody: "把 Brief Builder、文件審查、HTML 與 MDX 匯出工具接進 Claude Desktop、Cursor 或任何支援 MCP 的 AI Client。",
      mcpInstallCommand: "npm install -g @z7589xxz758/briefly-mcp-server",
      mcpPackageLabel: "查看 npm package",
      mcpPackageUrl: "https://www.npmjs.com/package/@z7589xxz758/briefly-mcp-server",
      stackEyebrow: "Engineered For Modern Stacks",
      featuresTitle: "重新定義企劃書的",
      featuresTitleMuted: "撰寫體驗。",
      featuresBody: "透過高階視覺元件與模組化架構，不論是設計師、PM 還是開發者，都能以最符合直覺的方式建立規格。",
      workflowEyebrow: "Workflow",
      workflowTitle: "流暢的",
      workflowTitleMuted: "編輯流水線。",
      workflowBody: "從概念發想到最終交付，SlideX Briefly 將整個流程無縫串聯。每個階段都有專屬的工具與檢視模式。",
      bottomTitleLine1: "準備好升級你的",
      bottomTitleLine2: "專案企劃了嗎？",
      bottomBody: "不再使用零散的筆記軟體。開始使用 SlideX Briefly，打造專為現代團隊而生的 MDX Brief Builder。",
      bottomCta: "開啟 SlideX Briefly Builder",
      features: [
        ["模組化區塊編輯", "不再受限於死板的文件。使用結構化的區塊 (Blocks) 拼湊企劃，每個區塊都能獨立編輯與重複使用。"],
        ["原生 MDX 支援", "結合 Markdown 的簡潔與 React 元件的強大，讓文件具備動態表現力。"],
        ["即時高階預覽", "編輯的當下即時渲染成排版精美的終端文件格式，所見即所得。"],
        ["HTML 與 MDX 輸出", "企劃可以保持可編輯，也可以成為可分享的網頁文件。輸出格式只保留 HTML 與 MDX。"]
      ],
      workflow: [
        ["結構建構 (Builder)", "透過視覺化的介面拖曳區塊，快速搭起專案的骨架。"],
        ["屬性檢查 (Inspector)", "精細調整每個區塊的細節設定、欄位與特定 MDX 屬性。"],
        ["文件輸出 (Export)", "完成後輸出 HTML 成品，或保留 MDX 原始檔供團隊繼續編輯。"]
      ]
    },
    builder: {
      topBar: {
        hideSidebar: "隱藏側邊欄",
        showSidebar: "顯示側邊欄",
        projectName: "專案名稱",
        preview: "預覽",
        draft: "草稿",
        export: "匯出"
      },
      tools: {
        blocks: { label: "區塊", title: "內容區塊" },
        outline: { label: "大綱", title: "文件大綱" },
        design: { label: "佈景", title: "佈景主題" },
        settings: { label: "設定", title: "偏好設定" }
      },
      exportActions: {
        mdx: "匯出為 MDX",
        html: "匯出為 HTML",
        pdf: "匯出為 HTML",
        copy: "複製 MDX"
      },
      exportPanelBody: "匯出目前的 HTML 文件，或複製與下載 MDX 原始碼。",
      left: {
        added: "已在文件中",
        add: "點擊加入",
        core: "核心區塊",
        optional: "選填區塊",
        moveUp: "上移",
        moveDown: "下移",
        delete: "刪除",
        close: "關閉側邊欄",
        cardTheme: "卡片主題",
        minimalWhite: "白色",
        darkTech: "黑色",
        backgroundColor: "背景色彩",
        applyBackground: "套用背景色彩",
        backgroundImage: "背景圖片",
        backgroundPreview: "背景預覽",
        replace: "更換",
        remove: "移除",
        uploadBackground: "上傳背景圖片",
        processingImage: "圖片處理中...",
        fileTypes: "PNG, JPG 或 WebP",
        developerJson: "MDX 結構預覽"
      },
      preferences: {
        title: "偏好設定",
        appearance: "外觀",
        language: "語系",
        system: "自動",
        dark: "深色",
        light: "淺色",
        zhTw: "繁中",
        english: "English"
      },
      inspector: {
        properties: "屬性設定",
        close: "關閉檢視器",
        selectedBlock: "選取的區塊",
        core: "核心",
        optional: "選填",
        blockBackground: "區塊背景",
        textColor: "文字顏色",
        layoutLabel: "排版 (區塊層級)",
        layoutFull: "全寬",
        layoutHalfLeft: "半寬 (靠左)",
        layoutHalfRight: "半寬 (靠右)"
      },
      mobile: {
        blocks: "區塊",
        preview: "預覽",
        settings: "設定",
        export: "匯出",
        emptyTitle: "未選取任何區塊",
        emptyBody: "在預覽畫面中點擊任一區塊即可開啟檢視器。"
      },
      toasts: {
        exportedMdx: "已匯出 MDX",
        exportedHtml: "已匯出 HTML",
        preparingPdf: "正在準備 HTML",
        copiedMdx: "已複製 MDX",
        copyFailed: "無法複製，請改用匯出 MDX"
      }
    },
    sectionEditor: {
      editLabel: "編輯",
      inlineHelp: "編輯內容將會更新至預覽畫面與匯出文件中。",
      unset: "未設定",
      listHelper: "每一行為一個項目。",
      noTags: "尚未加入標籤。",
      customTag: "自訂標籤",
      add: "加入",
      remove: "移除",
      referenceDefault: "參考資料",
      referenceLinks: "參考連結",
      addLink: "新增連結",
      displayName: "顯示名稱",
      url: "URL 網址",
      noLinks: "尚未新增連結。",
      referenceImages: "參考圖片",
      uploadImage: "上傳圖片",
      processing: "處理中...",
      referenceImageAlt: "參考圖片",
      imageCaption: "圖片說明",
      imageLimit: "最多上傳 5 張圖片。這些圖片僅會儲存在您的瀏覽器記憶體中。",
      teamRoster: "團隊陣容",
      addMember: "新增成員",
      name: "姓名",
      role: "職稱",
      raciType: "RACI 角色",
      raciLabels: {
        responsible: "負責人 (R)",
        accountable: "當責者 (A)",
        consulted: "諮詢者 (C)",
        informed: "知情者 (I)"
      },
      noMembers: "尚未新增團隊成員。",
      coverImage: "封面圖片",
      coverImageHelp: "上傳後會自動壓縮尺寸與檔案大小，避免文件變慢。",
      replace: "更換",
      uploadClick: "點擊上傳圖片",
      faq: "常見問題",
      addQuestion: "新增問題",
      questionPlaceholder: "輸入問題",
      answerPlaceholder: "輸入答案",
      noFaq: "尚未新增常見問題。",
      removeItem: "移除",
      timelineItems: "多段時間",
      timelineItemsHelp: "可加入多個時間點、期間或重要節點。",
      timelineItemDefault: "新的時間節點",
      addTime: "新增時間",
      timelineLabel: "節點名稱",
      timelineDate: "開始時間",
      timelineEndDate: "結束時間",
      timelineNote: "補充說明",
      noTimelineItems: "尚未新增時間節點。",
      attachments: "附件",
      attachmentsHelp: "可上傳 PDF、圖片、簡報或其他參考檔案。",
      uploadFiles: "上傳附件",
      noAttachments: "尚未上傳附件。",
      fileTooLarge: "檔案過大，請使用 2.5MB 以下的檔案。",
      unknownFileType: "未知格式",
      fields: {
        background: ["背景脈絡", "為什麼要啟動這個專案？契機是什麼？"],
        contextNote: ["補充說明", "讀者在評估專案前，還需要了解哪些背景資訊？"],
        primaryGoal: ["核心目標", "這個專案現階段最想達成的目標是什麼？"],
        secondaryGoals: ["次要目標", ""],
        successSignal: ["成功標準", "如何判斷這個專案是成功的？"],
        currentProgress: ["目前進度", ""],
        progressNote: ["進度說明", ""],
        nextStep: ["下一步", ""],
        lookingFor: ["尋找對象", ""],
        idealCollaborator: ["理想的合作夥伴", ""],
        helpNeeded: ["需要協助的領域", ""],
        collaborationModel: ["合作模式", ""],
        budgetOrReward: ["預算或報酬", ""],
        timeline: ["預計時程", ""],
        collaborationNote: ["合作備註", ""],
        contactName: ["聯絡人姓名", ""],
        contactEmail: ["電子郵件", ""],
        contactLink: ["相關連結 (如個人網站或社群)", ""],
        callToAction: ["行動呼籲按鈕 (CTA)", ""],
        problemStatement: ["問題陳述", ""],
        targetAudience: ["目標受眾", ""],
        whyItMatters: ["為何重要", ""],
        startDate: ["開始日期", ""],
        targetDate: ["目標完成日", ""],
        milestones: ["里程碑", ""],
        deliverables: ["預期交付物", ""],
        expectedOutputs: ["產出說明", ""],
        scopeNotes: ["範圍與限制", ""],
        availableAssets: ["可用資源", ""],
        filesOrLinks: ["相關連結與檔案", ""],
        assetNotes: ["資源備註", ""],
        risks: ["潛在風險", ""],
        openQuestions: ["未解問題", ""],
        assumptions: ["待驗證假設", ""],
        targetUsers: ["目標使用者", ""],
        useCases: ["使用情境", ""],
        earlyAdopters: ["早期採用者", ""],
        keyMetrics: ["關鍵指標", ""],
        validationSignals: ["驗證訊號", ""],
        visionStatement: ["產品願景", ""],
        nonGoals: ["非目標 (Non-goals)", ""],
        outOfScope: ["範圍外 (Out of scope)", ""],
        dependencies: ["相依性 (Dependencies)", ""],
        mitigationPlans: ["緩解策略 (Mitigation plans)", ""],
        roles: ["角色與職責", ""],
        currentGaps: ["缺少的職位", ""],
        freeformNotes: ["附註與細節", ""],
        projectName: ["專案名稱", ""],
        oneLiner: ["一句話介紹", ""],
        category: ["分類", ""],
        stage: ["目前階段", ""],
        status: ["文件狀態", ""],
        owner: ["負責人", "專案或文件的負責人是誰？"],
        confidentiality: ["機密等級", "例如：公開、內部、機密"],
        totalBudget: ["總預算或資源", "預計花費的總預算、工時或硬體資源"],
        budgetNotes: ["預算分配說明", "資源如何分配？或有什麼限制？"],
        decisionNotes: ["決策背景說明", "這些決策是在什麼時空背景下做出的？"]
      },
      addBudgetItem: "新增資源項目",
      noBudgetItems: "尚未新增預算項目。",
      addDecision: "新增決策",
      noDecisions: "尚未新增決策紀錄。",
      decisionPending: "討論中",
      decisionApproved: "已通過",
      decisionRejected: "已否決",
      budgetCategory: "類別",
      budgetAmount: "金額 / 數量",
      budgetNote: "備註"
    },
    preview: {
      defaultPlaceholder: "點擊開始編輯...",
      toolbar: {
        bold: "粗體",
        italic: "斜體",
        strike: "刪除線",
        heading2: "標題二",
        heading3: "標題三",
        bulletList: "無序清單",
        orderedList: "有序清單",
        quote: "引用區塊"
      },
      replace: "更換",
      remove: "移除",
      processing: "處理中...",
      logoLabel: "加入 Logo",
      replaceCover: "更換封面",
      addCover: "+ 加入封面圖片 (自動滿版裁切)",
      footerPlaceholder: "例如：如果您有興趣，請於 2026 年 4 月 15 日前將提案寄至 info@acme.com",
      addContent: "點擊此處新增內容。",
      editing: "編輯中",
      contactName: "聯絡人姓名",
      referenceLink: "參考連結",
      referenceImage: "參考圖片",
      memberName: "成員名稱",
      memberRole: "角色",
      question: "問題",
      answer: "答案",
      attachment: "附件",
      download: "下載附件",
      placeholders: {
        background: "為什麼要啟動這個專案？",
        contextNote: "有哪些重要的背景脈絡？",
        primaryGoal: "專案的核心目標是什麼？",
        successSignal: "如何判斷專案是否成功？",
        progressNote: "目前的進度說明...",
        nextStep: "接下來的計畫...",
        idealCollaborator: "理想的合作對象描述...",
        budgetOrReward: "預算或報酬...",
        timeline: "時程規劃...",
        collaborationNote: "合作模式的細節...",
        problemStatement: "想解決的問題是什麼？",
        targetAudience: "目標受眾是誰？",
        whyItMatters: "為什麼這個問題很重要？",
        expectedOutputs: "預期的產出物...",
        scopeNotes: "範圍與限制備註...",
        targetUsers: "目標使用者...",
        earlyAdopters: "早期採用者...",
        freeformNotes: "其他補充資訊...",
        visionStatement: "產品願景描述..."
      }
    }
  },
  en: {
    landing: {
      heroBody: "Build project briefs faster with MDX. Turn loose ideas into a structured brief, preview the finished document on canvas, then export MDX or HTML.",
      primaryCta: "Start Using SlideX Briefly",
      secondaryCta: "Explore Features",
      mcpInstallEyebrow: "Briefly MCP Server",
      mcpInstallTitle: "Install Briefly MCP with npm.",
      mcpInstallBody: "Connect Brief Builder, document review, HTML export, and MDX export tools to Claude Desktop, Cursor, or any MCP-capable AI client.",
      mcpInstallCommand: "npm install -g @z7589xxz758/briefly-mcp-server",
      mcpPackageLabel: "Open npm package",
      mcpPackageUrl: "https://www.npmjs.com/package/@z7589xxz758/briefly-mcp-server",
      stackEyebrow: "Engineered For Modern Stacks",
      featuresTitle: "Redefine the",
      featuresTitleMuted: "brief-writing experience.",
      featuresBody: "With polished visual components and a modular structure, designers, PMs, and developers can create specs in a way that feels direct and natural.",
      workflowEyebrow: "Workflow",
      workflowTitle: "A smoother",
      workflowTitleMuted: "editing pipeline.",
      workflowBody: "From early concept to final handoff, SlideX Briefly keeps the whole flow connected with dedicated tools and views for every stage.",
      bottomTitleLine1: "Ready to upgrade",
      bottomTitleLine2: "your project brief?",
      bottomBody: "Move beyond scattered notes. Start with SlideX Briefly and build an MDX brief builder made for modern teams.",
      bottomCta: "Open SlideX Briefly Builder",
      features: [
        ["Modular Block Editing", "Stop fighting rigid documents. Compose briefs with structured blocks that can be edited and reused independently."],
        ["Native MDX Support", "Combine Markdown simplicity with React component power so documents can stay expressive and dynamic."],
        ["Live Premium Preview", "Render your edits immediately into a polished final document format."],
        ["HTML and MDX Export", "Briefs stay editable and can become shareable web documents. The output surface stays focused on HTML and MDX."]
      ],
      workflow: [
        ["Structure Builder", "Drag blocks visually and assemble the project skeleton quickly."],
        ["Property Inspector", "Fine-tune each block's fields, details, and MDX-specific attributes."],
        ["Document Export", "Export a polished HTML document, or keep the MDX source editable for the team."]
      ]
    },
    builder: {
      topBar: {
        hideSidebar: "Hide sidebar",
        showSidebar: "Show sidebar",
        projectName: "Project name",
        preview: "Preview",
        draft: "Draft",
        export: "Export"
      },
      tools: {
        blocks: { label: "Blocks", title: "Content Blocks" },
        outline: { label: "Outline", title: "Document Outline" },
        design: { label: "Theme", title: "Theme" },
        settings: { label: "Settings", title: "Preferences" }
      },
      exportActions: {
        mdx: "Export as MDX",
        html: "Export as HTML",
        pdf: "Export as HTML",
        copy: "Copy MDX"
      },
      exportPanelBody: "Export the current HTML document, or copy and download the generated MDX source.",
      left: {
        added: "In document",
        add: "Click to add",
        core: "Core block",
        optional: "Optional block",
        moveUp: "Move up",
        moveDown: "Move down",
        delete: "Delete",
        close: "Close sidebar",
        cardTheme: "Card theme",
        minimalWhite: "White",
        darkTech: "Black",
        backgroundColor: "Background colors",
        applyBackground: "Apply background color",
        backgroundImage: "Background image",
        backgroundPreview: "Background preview",
        replace: "Replace",
        remove: "Remove",
        uploadBackground: "Upload background image",
        processingImage: "Processing image...",
        fileTypes: "PNG, JPG, or WebP",
        developerJson: "MDX structure preview"
      },
      preferences: {
        title: "Preferences",
        appearance: "Appearance",
        language: "Language",
        system: "Auto",
        dark: "Dark",
        light: "Light",
        zhTw: "繁中",
        english: "English"
      },
      inspector: {
        properties: "Properties",
        close: "Close inspector",
        selectedBlock: "Selected block",
        core: "Core",
        optional: "Optional",
        blockBackground: "Block background",
        textColor: "Text color",
        layoutLabel: "Layout (Block Level)",
        layoutFull: "Full Width",
        layoutHalfLeft: "Half Width (Left)",
        layoutHalfRight: "Half Width (Right)"
      },
      mobile: {
        blocks: "Blocks",
        preview: "Preview",
        settings: "Settings",
        export: "Export",
        emptyTitle: "No block selected",
        emptyBody: "Select a block in the preview to open the inspector."
      },
      toasts: {
        exportedMdx: "MDX exported",
        exportedHtml: "HTML exported",
        preparingPdf: "Preparing HTML",
        copiedMdx: "MDX copied",
        copyFailed: "Could not copy. Use Export as MDX instead."
      }
    },
    sectionEditor: {
      editLabel: "Edit",
      inlineHelp: "Changes update the preview and exported document.",
      unset: "Not set",
      listHelper: "One item per line.",
      noTags: "No tags added.",
      customTag: "Custom tag",
      add: "Add",
      remove: "Remove",
      referenceDefault: "Reference",
      referenceLinks: "Reference links",
      addLink: "Add link",
      displayName: "Display name",
      url: "URL",
      noLinks: "No links added.",
      referenceImages: "Reference images",
      uploadImage: "Upload image",
      processing: "Processing...",
      referenceImageAlt: "Reference image",
      imageCaption: "Image caption",
      imageLimit: "Upload up to 5 images. They are stored only in browser memory.",
      teamRoster: "Team roster",
      addMember: "Add member",
      name: "Name",
      role: "Role",
      raciType: "RACI Role",
      raciLabels: {
        responsible: "Responsible (R)",
        accountable: "Accountable (A)",
        consulted: "Consulted (C)",
        informed: "Informed (I)"
      },
      noMembers: "No team members added.",
      coverImage: "Cover image",
      coverImageHelp: "Images are compressed automatically so the document stays fast.",
      replace: "Replace",
      uploadClick: "Click to upload image",
      faq: "FAQ",
      addQuestion: "Add question",
      questionPlaceholder: "Enter a question",
      answerPlaceholder: "Enter an answer",
      noFaq: "No FAQ items added.",
      removeItem: "Remove",
      timelineItems: "Timeline items",
      timelineItemsHelp: "Add multiple dates, ranges, or key moments.",
      timelineItemDefault: "New timeline item",
      addTime: "Add time",
      timelineLabel: "Item name",
      timelineDate: "Start date",
      timelineEndDate: "End date",
      timelineNote: "Note",
      noTimelineItems: "No timeline items added.",
      attachments: "Attachments",
      attachmentsHelp: "Upload PDFs, images, decks, or other supporting files.",
      uploadFiles: "Upload files",
      noAttachments: "No attachments uploaded.",
      fileTooLarge: "File is too large. Use files under 2.5MB.",
      unknownFileType: "Unknown type",
      fields: {
        background: ["Background", "Why start this project? What sparked it?"],
        contextNote: ["Context note", "What should readers know before evaluating the project?"],
        primaryGoal: ["Primary goal", "What is the most important goal right now?"],
        secondaryGoals: ["Secondary goals", ""],
        successSignal: ["Success signal", "How will you know this project is working?"],
        currentProgress: ["Current progress", ""],
        progressNote: ["Progress note", ""],
        nextStep: ["Next step", ""],
        lookingFor: ["Looking for", ""],
        idealCollaborator: ["Ideal collaborator", ""],
        helpNeeded: ["Help needed", ""],
        collaborationModel: ["Collaboration model", ""],
        budgetOrReward: ["Budget or reward", ""],
        timeline: ["Timeline", ""],
        collaborationNote: ["Collaboration note", ""],
        contactName: ["Contact name", ""],
        contactEmail: ["Email", ""],
        contactLink: ["Related link (website or social)", ""],
        callToAction: ["Call-to-action button", ""],
        problemStatement: ["Problem statement", ""],
        targetAudience: ["Target audience", ""],
        whyItMatters: ["Why it matters", ""],
        startDate: ["Start date", ""],
        targetDate: ["Target date", ""],
        milestones: ["Milestones", ""],
        deliverables: ["Deliverables", ""],
        expectedOutputs: ["Output notes", ""],
        scopeNotes: ["Scope and limits", ""],
        availableAssets: ["Available assets", ""],
        filesOrLinks: ["Links and files", ""],
        assetNotes: ["Asset notes", ""],
        risks: ["Risks", ""],
        openQuestions: ["Open questions", ""],
        assumptions: ["Assumptions to validate", ""],
        targetUsers: ["Target users", ""],
        useCases: ["Use cases", ""],
        earlyAdopters: ["Early adopters", ""],
        keyMetrics: ["Key metrics", ""],
        validationSignals: ["Validation signals", ""],
        visionStatement: ["Vision statement", ""],
        nonGoals: ["Non-goals", ""],
        outOfScope: ["Out of scope", ""],
        dependencies: ["Dependencies", ""],
        mitigationPlans: ["Mitigation plans", ""],
        roles: ["Roles and responsibilities", ""],
        currentGaps: ["Current gaps", ""],
        freeformNotes: ["Notes and details", ""],
        projectName: ["Project Name", ""],
        oneLiner: ["One-liner", ""],
        category: ["Category", ""],
        stage: ["Stage", ""],
        status: ["Status", ""],
        owner: ["Owner", "Who is responsible for this project?"],
        confidentiality: ["Confidentiality", "e.g. Public, Internal, Confidential"],
        totalBudget: ["Total Budget", "Estimated cost, man-hours, or resources"],
        budgetNotes: ["Budget Notes", "How are resources allocated? Any constraints?"],
        decisionNotes: ["Decision Context", "What's the background of these decisions?"]
      },
      addBudgetItem: "Add Resource",
      noBudgetItems: "No budget items added yet.",
      addDecision: "Add decision",
      noDecisions: "No decisions added.",
      decisionPending: "Pending",
      decisionApproved: "Approved",
      decisionRejected: "Rejected",
      budgetCategory: "Category",
      budgetAmount: "Amount",
      budgetNote: "Note"
    },
    preview: {
      defaultPlaceholder: "Click to start editing...",
      toolbar: {
        bold: "Bold",
        italic: "Italic",
        strike: "Strikethrough",
        heading2: "Heading 2",
        heading3: "Heading 3",
        bulletList: "Bullet list",
        orderedList: "Numbered list",
        quote: "Quote"
      },
      replace: "Replace",
      remove: "Remove",
      processing: "Processing...",
      logoLabel: "Add logo",
      replaceCover: "Replace cover",
      addCover: "+ Add cover image (auto full-bleed crop)",
      footerPlaceholder: "Example: If you are interested, please send a proposal to info@acme.com by April 15, 2025",
      addContent: "Click here to add content.",
      editing: "Editing",
      contactName: "Contact name",
      referenceLink: "Reference link",
      referenceImage: "Reference image",
      memberName: "Member name",
      memberRole: "Role",
      question: "Question",
      answer: "Answer",
      attachment: "Attachment",
      download: "Download file",
      placeholders: {
        background: "Why start this project?",
        contextNote: "What important context should readers know?",
        primaryGoal: "What is the core project goal?",
        successSignal: "How will success be measured?",
        progressNote: "Current progress...",
        nextStep: "Next plan...",
        idealCollaborator: "Describe the ideal collaborator...",
        budgetOrReward: "Budget or reward...",
        timeline: "Timeline...",
        collaborationNote: "Collaboration details...",
        problemStatement: "What problem are you solving?",
        targetAudience: "Who is the target audience?",
        whyItMatters: "Why does this problem matter?",
        expectedOutputs: "Expected outputs...",
        scopeNotes: "Scope and constraints...",
        targetUsers: "Target users...",
        earlyAdopters: "Early adopters...",
        freeformNotes: "Other notes and details...",
        visionStatement: "Vision description..."
      }
    }
  }
} as const;

const sectionGroupLabels: Record<BrieflyLocale, Record<SectionGroup, string>> = {
  "zh-TW": {
    "Essential Blocks": "核心區塊",
    "Project Details": "專案細節",
    "Advanced Blocks": "進階區塊"
  },
  en: {
    "Essential Blocks": "Essential Blocks",
    "Project Details": "Project Details",
    "Advanced Blocks": "Advanced Blocks"
  }
};

const sectionLabels: Record<BrieflyLocale, Record<SectionType, { title: string; description: string }>> = {
  "zh-TW": {
    cover: { title: "封面與簡介", description: "專案名稱、一句話介紹、分類、階段與狀態。" },
    background: { title: "背景與問題陳述", description: "為什麼要啟動這個專案？有哪些重要的背景資訊？" },
    goal: { title: "目標與成功標準", description: "專案的下一步是什麼？成功的定義為何？" },
    timeline: { title: "時程規劃", description: "預計開始時間、目標完成日與重要里程碑。" },
    deliverables: { title: "預期產出與範圍", description: "專案的預期產出物與範圍說明。" },
    resources: { title: "參考資源與附錄", description: "現有的檔案、連結、設計資產或筆記。" },
    risks: { title: "風險與假設", description: "潛在風險、尚未解決的問題或需要驗證的假設。" },
    audience: { title: "目標受眾", description: "目標使用者、使用情境與早期採用者。" },
    team: { title: "團隊陣容", description: "目前團隊成員、角色，以及尚缺的職位。" },
    faq: { title: "常見問題", description: "讀者可能會想問的問題與解答。" },
    budget: { title: "預算與資源", description: "預估專案所需的預算與資源配置。" },
    decisions: { title: "決策紀錄", description: "記錄重要的專案決策、理由與決策者。" }
  },
  en: {
    cover: { title: "Cover / Snapshot", description: "Project name, one-liner, category, stage, and status." },
    background: { title: "Background & Problem", description: "Why does this project exist, and what context matters?" },
    goal: { title: "Goal / Success Criteria", description: "The next target and the definition of success." },
    timeline: { title: "Timeline", description: "Start date, target date, and milestones." },
    deliverables: { title: "Deliverables & Scope", description: "Expected outputs and scope." },
    resources: { title: "Resources / Appendix", description: "Existing files, links, design assets, or notes." },
    risks: { title: "Risks / Assumptions", description: "Risks, unresolved questions, or assumptions to validate." },
    audience: { title: "Target Audience", description: "Target users, usage scenarios, and early adopters." },
    team: { title: "Team", description: "Current team members, roles, and gaps." },
    faq: { title: "FAQ", description: "Questions and answers readers may have." },
    budget: { title: "Budget & Resources", description: "Estimated budget and resource allocation." },
    decisions: { title: "Decision Log", description: "Important project decisions and rationale." }
  }
};

const optionLabels: Record<BrieflyLocale, Record<string, string>> = {
  "zh-TW": {
    "internal": "內部",
    "confidential": "機密",
    "public": "公開"
  },
  en: {
    "internal": "Internal",
    "confidential": "Confidential",
    "public": "Public",
    "AI 工具": "AI Tool",
    "網站": "Website",
    "品牌與視覺": "Brand / Visual Identity",
    "內容產品": "Content Product",
    "課程與知識產品": "Course / Knowledge Product",
    "社群": "Community",
    "開源專案": "Open Source Project",
    "自動化": "Automation",
    "商業專案": "Business Project",
    "其他": "Other",
    "點子發想": "Idea",
    "規劃中": "Planning",
    "原型製作": "Prototype",
    "MVP (最小可行性產品)": "MVP",
    "已上線": "Launched",
    "已有使用者": "Has Users",
    "已有營收": "Has Revenue",
    "成長期": "Growth",
    "需要重新設計或優化": "Needs Redesign / Optimization",
    "草稿": "Draft",
    "尋求回饋": "Seeking Feedback",
    "開發中": "In Development",
    "已發布": "Published",
    "暫停": "Paused",
    "尋找合作夥伴": "Seeking Partners",
    "開放 Beta 測試": "Open Beta",
    "私人專案": "Private Project",
    "僅有點子": "Idea Only",
    "需求已起草": "Requirements Drafted",
    "線框圖已完成": "Wireframes Ready",
    "原型已完成": "Prototype Ready",
    "可提供 Demo": "Demo Available",
    "網站已上線": "Website Live",
    "已有設計素材": "Design Assets Ready",
    "已有合作夥伴": "Partners Involved",
    "設計師": "Designer",
    "開發者": "Developer",
    "產品合夥人": "Product Partner",
    "行銷人員": "Marketer",
    "內容創作者": "Content Creator",
    "AI 工程師": "AI Engineer",
    "No-code 建設者": "No-code Builder",
    "Beta 測試者": "Beta Tester",
    "產品回饋": "Product Feedback",
    "早期客戶": "Early Customer",
    "顧問或導師": "Advisor / Mentor",
    "共同創辦人": "Co-founder",
    "工作室或團隊": "Pitch / Team",
    "客戶或商業夥伴": "Client / Business Partner",
    "前端開發": "Frontend Development",
    "後端開發": "Backend Development",
    "產品策略": "Product Strategy",
    "品牌設計": "Brand Design",
    "行銷與成長": "Marketing / Growth",
    "內容創作": "Content Creation",
    "使用者測試": "User Testing",
    "商業模式": "Business Model",
    "技術諮詢": "Technical Consulting",
    "專案管理": "Project Management",
    "銷售與合作夥伴": "Sales / Partnerships",
    "付費合作": "Paid Collaboration",
    "共同打造": "Co-building",
    "利潤共享": "Revenue Share",
    "股權或共同創辦": "Equity / Co-founder",
    "接案": "Freelance Work",
    "顧問回饋": "Advisory Feedback",
    "技能交換": "Skill Exchange",
    "開源貢獻": "Open Source Contribution",
    "商業合作": "Business Partnership",
    "無預算，僅交流或回饋": "No Budget, Feedback Only",
    "1 萬以內": "Under NT$10k",
    "1 萬 - 3 萬": "NT$10k - 30k",
    "3 萬 - 10 萬": "NT$30k - 100k",
    "10 萬 - 30 萬": "NT$100k - 300k",
    "30 萬以上": "NT$300k+",
    "利潤共享或股權": "Revenue Share / Equity",
    "尚未確定": "Not Decided",
    "兩週內": "Within 2 Weeks",
    "一個月內": "Within 1 Month",
    "1-3 個月": "1-3 Months",
    "長期開放合作": "Open Long Term",
    "目前僅為展示": "Showcase Only",
    "我很感興趣": "I'm Interested",
    "提供回饋": "Give Feedback",
    "加入 Beta 測試": "Join Beta",
    "討論合作": "Discuss Collaboration",
    "索取更多資訊": "Request More Info"
  }
};

export function getBrieflyCopy(locale: BrieflyLocale) {
  return brieflyCopy[locale];
}

export function getSectionGroupLabel(group: SectionGroup, locale: BrieflyLocale) {
  return sectionGroupLabels[locale][group] ?? group;
}

export function getSectionCopy(type: SectionType, locale: BrieflyLocale) {
  return sectionLabels[locale][type];
}

export function getOptionLabel(value: string, locale: BrieflyLocale) {
  return optionLabels[locale][value] ?? value;
}
